import os, requests, subprocess

sDownloads = True
sUsrDir = os.path.expanduser('~')

# Basically changes directory based on sDownloads
def fnChangeDir():
    download_dir = os.path.join(sUsrDir, 'Downloads')
    if not sDownloads:
        download_dir = os.path.join(sUsrDir, '.minecraft')
    if not os.path.exists(download_dir):
        os.makedirs(download_dir)
    os.chdir(download_dir)
    
    
def fnForgeInstall():
    # Grabs the forge installer and runs it
    fnChangeDir()
    print('Download directory ' + (os.getcwd()))
    
    url = 'https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.2.8/forge-1.19.2-43.2.8-installer.jar'
    r = requests.get(url, allow_redirects = True)
    with open('forge-installer.jar', 'wb') as f:
        f.write(r.content)
    
    # the installer part generated by chatgpt
    proc = subprocess.Popen(['java', '-jar', 'forge-installer.jar'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    # Wait for the program to finish and capture the output
    out, err = proc.communicate()
    # Print the output
    print(out.decode('utf-8'))